version: "3.7"

services:

    client:
        image: node:12-alpine
        command: sh -c "npm install && npx vue-cli-service serve"
        ports:
            - 8080:8080
        working_dir: /ezpoll/client
        volumes:
            - ./ezpollclient:/ezpoll/client

    socket-server:
        image: node:12-alpine
        command: sh -c "npm install && npm run start"
        ports:
            - 3000:3000
        working_dir: /ezpoll/socket-server
        volumes:
            - ./ezpollsocketserver:/ezpoll/socket-server

    python-api:
        image: python
        command: sh -c "pip3 install -r requirements.txt && python api.py"
        ports:
            - 5000:5000
        working_dir: /ezpoll/python-api
        volumes:
            - ./server:/ezpoll/python-api

    mysql-db:
        image: mysql:5.7
        ports:
            - 3306:3306
        working_dir: /docker-entrypoint-initdb.d
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
