# Picks free host ports into .env (created on first run), then runs docker compose.
#   .\run.ps1            docker compose up --build -d, then print the URLs
#   .\run.ps1 <args>     docker compose <args> (for example: .\run.ps1 down)
param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ComposeArgs)
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

# Host port variables and their preferred defaults.
$Ports = [ordered]@{ CLIENT_PORT = 8080; SOCKET_PORT = 3000; API_PORT = 5000; MYSQL_PORT = 3307; PHPMYADMIN_PORT = 8083 }

function Show-Urls {
    Write-Host "EZPoll client: http://localhost:$(Get-PortOf CLIENT_PORT)"
    Write-Host "phpMyAdmin:    http://localhost:$(Get-PortOf PHPMYADMIN_PORT)"
    Write-Host "Socket.io:     http://localhost:$(Get-PortOf SOCKET_PORT)  (used by the client)"
    Write-Host "Python API:    http://127.0.0.1:$(Get-PortOf API_PORT)  (needs the internal secret header)"
    Write-Host "MySQL:         127.0.0.1:$(Get-PortOf MYSQL_PORT)"
}

# ---- generic part (identical in every repo) ----
$EnvFile = Join-Path $PSScriptRoot '.env'

function Test-PortBusy([int]$Port) {
    $client = New-Object Net.Sockets.TcpClient
    try {
        $wait = $client.BeginConnect('127.0.0.1', $Port, $null, $null)
        if ($wait.AsyncWaitHandle.WaitOne(500) -and $client.Connected) { return $true }
    } catch { } finally { $client.Close() }
    try {
        $listener = [Net.Sockets.TcpListener]::new([Net.IPAddress]::Any, $Port)
        $listener.Start(); $listener.Stop()
        return $false
    } catch { return $true }
}

function Get-EnvLines { if (Test-Path $EnvFile) { [IO.File]::ReadAllLines($EnvFile) } else { @() } }

function Get-EnvValue([string]$Key) {
    $hit = Get-EnvLines | Where-Object { $_ -like "$Key=*" } | Select-Object -Last 1
    if ($hit) { $hit.Substring($Key.Length + 1).Trim() } else { '' }
}

function Set-EnvValue([string]$Key, [string]$Value) {
    $lines = @(Get-EnvLines)
    $found = $false
    $out = foreach ($line in $lines) {
        if ($line -like "$Key=*") { $found = $true; "$Key=$Value" } else { $line }
    }
    if (-not $found) { $out = @($lines) + "$Key=$Value" }
    [IO.File]::WriteAllText($EnvFile, ((@($out) -join "`n") + "`n"), (New-Object Text.UTF8Encoding $false))
}

function Get-PortOf([string]$Key) {
    $v = Get-EnvValue $Key
    if ($v) { $v } else { $Ports[$Key] }
}

function Select-Ports {
    if (-not (Test-Path $EnvFile)) {
        [IO.File]::WriteAllText($EnvFile, "# Generated by run.ps1: host ports chosen because the defaults were busy or to avoid`n# clashes with other stacks. Edit to pin ports, or delete this file to pick again.`n", (New-Object Text.UTF8Encoding $false))
    }
    $picked = @()
    foreach ($var in $Ports.Keys) {
        $port = 0
        if (-not [int]::TryParse((Get-EnvValue $var), [ref]$port) -or $port -lt 1) { $port = $Ports[$var] }
        $start = $port
        while ($picked -contains $port -or (Test-PortBusy $port)) { $port++ }
        $picked += $port
        if ($port -ne $start) { Write-Host "${var}: port $start is busy, using $port" }
        if ((Get-EnvValue $var) -ne "$port") { Set-EnvValue $var "$port" }
    }
}

$build = @('--build')
if (docker compose ps --status running -q) {
    Write-Host 'Stack already running: leaving ports unchanged and skipping the rebuild.'
    Write-Host '(To rebuild after code changes: .\run.ps1 up --build -d)'
    $build = @()
} else {
    Select-Ports
    if (Get-EnvLines | Where-Object { $_ -match '^(ALLOWED_ORIGINS|PUBLIC_SOCKET_URL)=' }) {
        Write-Host 'Note: .env sets ALLOWED_ORIGINS or PUBLIC_SOCKET_URL explicitly. They must match the ports above.'
    }
}

if ($ComposeArgs) {
    docker compose @ComposeArgs
    exit $LASTEXITCODE
}
docker compose up @build -d
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Show-Urls
